package ser322;

import java.io.FileReader;
import java.io.IOException;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.sax.SAXSource;

import org.xml.sax.InputSource;
import org.xml.sax.SAXException;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import org.w3c.dom.Node;

import javax.xml.xpath.XPath;
import javax.xml.xpath.XPathConstants;
import javax.xml.xpath.XPathExpression;
import javax.xml.xpath.XPathExpressionException;
import javax.xml.xpath.XPathFactory;

/*
Program scans test.xml file and returns results matching a given department
*/
public class JdbcLab2 {
    public static void main(String args[]) {
        //If there is no department number, the program cannot run
        if (args.length < 1) {
			System.out.println("USAGE: java ser322.JdbcLab2 <DeptNo>");
			System.exit(0);
		}
        
        //New xpath
        XPathFactory xpathFactory = XPathFactory.newInstance();
        XPath xpath = xpathFactory.newXPath();

        //Source is test.xml, the file generated by the export function in the first task
        InputSource source = new InputSource("test.xml");

        //Setup for reading doc
        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
        factory.setIgnoringElementContentWhitespace(true);
        factory.setValidating(false);

        Document doc = null; 
        
        //Reading doc and error handling.
        try { 
            DocumentBuilder builder = factory.newDocumentBuilder();
            doc = builder.parse(source);
        } catch (ParserConfigurationException e) {
            System.out.println("There was a problem with opening the document.");
            System.exit(0);
        } catch (SAXException e) {
            System.out.println("There was a problem with the XML input.");
            System.exit(0);
        } catch (IOException e) {
            System.out.println("There was a problem with the file output.");
            System.exit(0);
        } 

        //makes a root for the xpath
        Element root = doc.getDocumentElement();
        root.normalize();

        //Executing query and retrieving info
        try { 
            NodeList emailNodes = (NodeList)xpath.evaluate("//product[MADE_BY=" + args[0] + "]/DESCRIP", root, XPathConstants.NODESET);
            for (int i=0; i < emailNodes.getLength(); i++) {
                Node emailNode = (Node) emailNodes.item(i);
                Node emailText = (Node)xpath.evaluate("text()", emailNode, XPathConstants.NODE);
                System.out.println("Product from Department " + args[0] + ": " + emailText.getNodeValue());
            }
        } catch (XPathExpressionException e) {
                System.out.println("There was a problem with the XML syntax.");
                System.exit(0);
        } 
    }
}